package deepLearning;
import net.sf.javaml.core.Dataset;import net.sf.javaml.classification.Classifier;
import net.sf.javaml.core.Dataset;
import net.sf.javaml.core.Instance;
import net.sf.javaml.tools.data.FileHandler;
import java.io.BufferedReader;import java.io.File;import java.io.FileInputStream;import java.io.FileReader;import java.io.FileWriter;import java.text.DecimalFormat;import java.util.ArrayList;import java.util.Arrays;import java.util.Iterator;import java.util.List;
import org.apache.poi.xssf.usermodel.XSSFSheet;import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import libsvm.LibSVM;
public class SvmLotter { public static void main(String[] args) throws Exception {
        /* Load a data set */  File lofile = new File(System.getProperty("user.dir")+"/src/resources/lottery.data");   String csvFile = "C:/trainData.csv";   String trainFormatFile = "C:/trainFormatFile.csv";   FileWriter writer = new FileWriter(csvFile);   FileWriter writerFormat = new FileWriter(trainFormatFile);     // Finds the workbook instance for XLSX file  BufferedReader br=new BufferedReader(new FileReader(lofile));           String date="";     String[] DataToArray=new String[7];     String[] winData=null;     String[] winDataBefore1=null;     String[] winDataBefore2=null;     int line=0;     int isWin=0;     int isWinBefore1=0;     int isWinBefore2=0;     int whichDay=0;     String line_str="";     StringBuffer output=null;    while((line_str=br.readLine())!=null){     line++;         System.out.println(line_str);     isWin=0;     isWinBefore1=0;     isWinBefore2=0;     DataToArray=line_str.split(",");     date=DataToArray[0];     whichDay=Integer.parseInt(DataToArray[1]);     int sum=0;     winDataBefore2=winDataBefore1;     winDataBefore1=winData;     winData= new String[]{DataToArray[2],DataToArray[3],DataToArray[4],DataToArray[5],DataToArray[6]};     if(line<3){      continue;     }          for (String number : winData){        sum += Integer.valueOf(number);     }     for(int i=1;i<40;i++){      output=new StringBuffer();      isWin=0;      isWinBefore1=0;      isWinBefore2=0;      if(Arrays.asList(winData).contains(String.valueOf(i))){              isWin=1;}      if(Arrays.asList(winDataBefore1).contains(String.valueOf(i))){              isWinBefore1=1;}      if(Arrays.asList(winDataBefore2).contains(String.valueOf(i))){          isWinBefore2=1;}      //日期,球號,預測0或1,當天星期幾,加總      //label,index:value      CSVUtils.writeLine(writer, Arrays.asList(date,String.valueOf(i),String.valueOf(whichDay),String.valueOf(isWin),String.valueOf(isWinBefore1),String.valueOf(isWinBefore2),String.valueOf(sum)));      //label 預測0或1,當天星期幾,加總,上1期有出現,上1期出現後加1      output.append(String.valueOf(isWin)+" 1:"+String.valueOf(whichDay)+" 2:"+String.valueOf(sum));      if(isWinBefore1==1){       output.append(" 3:"+String.valueOf(isWinBefore1));      }      if(isWinBefore2==1){       output.append(" 4:"+String.valueOf(isWinBefore2));      }      CSVUtils.writeLine(writerFormat, Arrays.asList(output.toString()));           }    }                              writer.flush();         writer.close();
             
    }
}
